// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.7
// source: proto/gateway.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OptimizationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Prompt         string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ModelRequested string                 `protobuf:"bytes,2,opt,name=model_requested,json=modelRequested,proto3" json:"model_requested,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrgId          string                 `protobuf:"bytes,4,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OptimizationRequest) Reset() {
	*x = OptimizationRequest{}
	mi := &file_proto_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizationRequest) ProtoMessage() {}

func (x *OptimizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizationRequest.ProtoReflect.Descriptor instead.
func (*OptimizationRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *OptimizationRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *OptimizationRequest) GetModelRequested() string {
	if x != nil {
		return x.ModelRequested
	}
	return ""
}

func (x *OptimizationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OptimizationRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type OptimizationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OptimizedPrompt string                 `protobuf:"bytes,1,opt,name=optimized_prompt,json=optimizedPrompt,proto3" json:"optimized_prompt,omitempty"`
	TargetModel     string                 `protobuf:"bytes,2,opt,name=target_model,json=targetModel,proto3" json:"target_model,omitempty"` // e.g., "gpt-4o-mini" or "gpt-oss-120b"
	ShouldUseOss    bool                   `protobuf:"varint,3,opt,name=should_use_oss,json=shouldUseOss,proto3" json:"should_use_oss,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OptimizationResponse) Reset() {
	*x = OptimizationResponse{}
	mi := &file_proto_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizationResponse) ProtoMessage() {}

func (x *OptimizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizationResponse.ProtoReflect.Descriptor instead.
func (*OptimizationResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *OptimizationResponse) GetOptimizedPrompt() string {
	if x != nil {
		return x.OptimizedPrompt
	}
	return ""
}

func (x *OptimizationResponse) GetTargetModel() string {
	if x != nil {
		return x.TargetModel
	}
	return ""
}

func (x *OptimizationResponse) GetShouldUseOss() bool {
	if x != nil {
		return x.ShouldUseOss
	}
	return false
}

var File_proto_gateway_proto protoreflect.FileDescriptor

const file_proto_gateway_proto_rawDesc = "" +
	"\n" +
	"\x13proto/gateway.proto\x12\agateway\"\x86\x01\n" +
	"\x13OptimizationRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12'\n" +
	"\x0fmodel_requested\x18\x02 \x01(\tR\x0emodelRequested\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x15\n" +
	"\x06org_id\x18\x04 \x01(\tR\x05orgId\"\x8a\x01\n" +
	"\x14OptimizationResponse\x12)\n" +
	"\x10optimized_prompt\x18\x01 \x01(\tR\x0foptimizedPrompt\x12!\n" +
	"\ftarget_model\x18\x02 \x01(\tR\vtargetModel\x12$\n" +
	"\x0eshould_use_oss\x18\x03 \x01(\bR\fshouldUseOss2\\\n" +
	"\tOptimizer\x12O\n" +
	"\x0eOptimizePrompt\x12\x1c.gateway.OptimizationRequest\x1a\x1d.gateway.OptimizationResponse\"\x00B1Z/github.com/abhinavtyagiO/ai-gateway-proxy/protob\x06proto3"

var (
	file_proto_gateway_proto_rawDescOnce sync.Once
	file_proto_gateway_proto_rawDescData []byte
)

func file_proto_gateway_proto_rawDescGZIP() []byte {
	file_proto_gateway_proto_rawDescOnce.Do(func() {
		file_proto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_rawDesc)))
	})
	return file_proto_gateway_proto_rawDescData
}

var file_proto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_gateway_proto_goTypes = []any{
	(*OptimizationRequest)(nil),  // 0: gateway.OptimizationRequest
	(*OptimizationResponse)(nil), // 1: gateway.OptimizationResponse
}
var file_proto_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.Optimizer.OptimizePrompt:input_type -> gateway.OptimizationRequest
	1, // 1: gateway.Optimizer.OptimizePrompt:output_type -> gateway.OptimizationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gateway_proto_init() }
func file_proto_gateway_proto_init() {
	if File_proto_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gateway_proto_goTypes,
		DependencyIndexes: file_proto_gateway_proto_depIdxs,
		MessageInfos:      file_proto_gateway_proto_msgTypes,
	}.Build()
	File_proto_gateway_proto = out.File
	file_proto_gateway_proto_goTypes = nil
	file_proto_gateway_proto_depIdxs = nil
}
