// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.7
// source: proto/gateway.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Optimizer_OptimizePrompt_FullMethodName = "/gateway.Optimizer/OptimizePrompt"
	Optimizer_UpdateCache_FullMethodName    = "/gateway.Optimizer/UpdateCache"
)

// OptimizerClient is the client API for Optimizer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OptimizerClient interface {
	OptimizePrompt(ctx context.Context, in *OptimizationRequest, opts ...grpc.CallOption) (*OptimizationResponse, error)
	UpdateCache(ctx context.Context, in *CacheUpdateRequest, opts ...grpc.CallOption) (*CacheUpdateResponse, error)
}

type optimizerClient struct {
	cc grpc.ClientConnInterface
}

func NewOptimizerClient(cc grpc.ClientConnInterface) OptimizerClient {
	return &optimizerClient{cc}
}

func (c *optimizerClient) OptimizePrompt(ctx context.Context, in *OptimizationRequest, opts ...grpc.CallOption) (*OptimizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OptimizationResponse)
	err := c.cc.Invoke(ctx, Optimizer_OptimizePrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *optimizerClient) UpdateCache(ctx context.Context, in *CacheUpdateRequest, opts ...grpc.CallOption) (*CacheUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CacheUpdateResponse)
	err := c.cc.Invoke(ctx, Optimizer_UpdateCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OptimizerServer is the server API for Optimizer service.
// All implementations must embed UnimplementedOptimizerServer
// for forward compatibility.
type OptimizerServer interface {
	OptimizePrompt(context.Context, *OptimizationRequest) (*OptimizationResponse, error)
	UpdateCache(context.Context, *CacheUpdateRequest) (*CacheUpdateResponse, error)
	mustEmbedUnimplementedOptimizerServer()
}

// UnimplementedOptimizerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOptimizerServer struct{}

func (UnimplementedOptimizerServer) OptimizePrompt(context.Context, *OptimizationRequest) (*OptimizationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OptimizePrompt not implemented")
}
func (UnimplementedOptimizerServer) UpdateCache(context.Context, *CacheUpdateRequest) (*CacheUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCache not implemented")
}
func (UnimplementedOptimizerServer) mustEmbedUnimplementedOptimizerServer() {}
func (UnimplementedOptimizerServer) testEmbeddedByValue()                   {}

// UnsafeOptimizerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OptimizerServer will
// result in compilation errors.
type UnsafeOptimizerServer interface {
	mustEmbedUnimplementedOptimizerServer()
}

func RegisterOptimizerServer(s grpc.ServiceRegistrar, srv OptimizerServer) {
	// If the following call panics, it indicates UnimplementedOptimizerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Optimizer_ServiceDesc, srv)
}

func _Optimizer_OptimizePrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptimizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizerServer).OptimizePrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Optimizer_OptimizePrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizerServer).OptimizePrompt(ctx, req.(*OptimizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Optimizer_UpdateCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizerServer).UpdateCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Optimizer_UpdateCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizerServer).UpdateCache(ctx, req.(*CacheUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Optimizer_ServiceDesc is the grpc.ServiceDesc for Optimizer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Optimizer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.Optimizer",
	HandlerType: (*OptimizerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OptimizePrompt",
			Handler:    _Optimizer_OptimizePrompt_Handler,
		},
		{
			MethodName: "UpdateCache",
			Handler:    _Optimizer_UpdateCache_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gateway.proto",
}
